name: check
on:
  push:
  pull_request:

jobs:
  test:
    name: Test with Python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox
      - if: ${{ matrix.py == '3.10' }}
        name: Generate coverage data
        run: .tox/py310/bin/coverage lcov -o coverage/lcov.info
      - if: ${{ matrix.py == '3.10' }}
        name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Setup python to build package
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install build
        run: python -m pip install build
      - uses: actions/checkout@v2
      - name: Build sdist and wheel
        run: python -m build -s -w . -o dist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}
